### ISSUE TITLE
希望可以增加编译更具有可读性JS扩展的编译选项

### ISSUE THREAD

**Issue by ChangingSelf** [sealdice/sealdice-js-ext-template#1]
模板中使用esbuild进行编译的两个npm scripts，编译出来的都是优化过但难以阅读的JS脚本，希望能让发布后的扩展能够具有更好的可读性，以便骰主们对其进行**个性化调整**以及**填写一些必要的key**。

目前我找到的可以增加可读性的esbuild选项：

- minify：设置为false，这样可以保留原本的缩进
- charset：设置为'utf8'，这样可以使得字符串不被转义为\u字符串，增加可读性

保留原本的注释也可以增加可读性，但不太清楚如何实现。

或许可以新增一个npm scripts，编译出这种可读性比较高的发布版本。

**Comment by Xiangze-Li** [comment]
这个功能或许可以满足你的需求 https://sealdice.github.io/sealdice-manual-next/advanced/edit_jsscript.html#%E6%B3%A8%E5%86%8C%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE%E9%A1%B9
